### ISSUE TITLE
Support net6.0-windows10.0.18362

### ISSUE THREAD

**Issue by rocksdanister** [ghost1372/SettingsUI#2]
Hi, thanks for this Library I am using it in my personal project.

I am using TargetFrameWorks `net6.0-windows10.0.18362` and having to build it myself as the nuget package is targeting `net6.0-windows10.0.19041.0`

Is it possible for you to downgrade to 18362 for the nuget package?

**Comment by ghost1372** [comment]
Hi @rocksdanister 
I uploaded a new nuget package with support TargetFrameWorks >= 17763 (1809)
