### ISSUE TITLE
WindowHelper : minimum size support

### ISSUE THREAD

**Issue by rocksdanister** [ghost1372/SettingsUI#4]
Support for setting MinWidth and MinHeight for Window.

WPF doc:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.minwidth?view=windowsdesktop-6.0
https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.minheight?view=windowsdesktop-6.0

**Comment by ghost1372** [comment]
Hi @rocksdanister 
Thank you for your suggestion
I added this feature
https://github.com/ghost1372/SettingsUI#window-heightwidth-minmax-size

**Comment by rocksdanister** [comment]
Thanks, looked at the commit maybe change SetWindowLong to SetWindowLongPtr?
http://www.pinvoke.net/default.aspx/user32/SetWindowLongPtr.html

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlonga
>This function has been superseded by the [SetWindowLongPtr](https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setwindowlongptra) function. To write code that is compatible with both 32-bit and 64-bit versions of Windows, use the SetWindowLongPtr function.

**Comment by ghost1372** [comment]
@rocksdanister  Done!
https://github.com/ghost1372/SettingsUI/commit/e7c5c9694c370793756a79f0aa58877a89726441

**Comment by ghost1372** [comment]
Done!
https://github.com/ghost1372/SettingsUI/commit/2ca67c33b47de5d7bac54aaaa729712c8c37e654
