### ISSUE TITLE
[Feature] Separating nuget package

### ISSUE THREAD

**Issue by Lightczx** [ghost1372/SettingsUI#5]
Currently SettingsUI only have single nuget package, and incluedes some unnecessary classes in.
I'm not saying that those utils are useless, but I just want a small package that only contains Setting UI controls.
I also found that some of the utils are in the CommunityToolkit.WinUI project.This causes some kind of code duplication.
In my opinion those utils should be placed in a separated package, and people can ref it if they really want.

I hope you can take my suggestions into consideration.

**Comment by ghost1372** [comment]
Hi @Lightczx Thanks for Suggestion.
I can not do that right now but I will think about it.
Maybe I could move the Tools section (Helper, Extensions) to another package.

**Comment by ghost1372** [comment]
Done
We added a new nuget package
SettingsUI.SettingsControls

**Comment by ghost1372** [comment]
Done
We added a new nuget package
WinUICommunity.SettingsUI

**Comment by johngagefaulkner** [comment]
> Done We added a new nuget package WinUICommunity.SettingsUI

Awesome to see you come back and implement this request 6+ months later. Far too often, people either forget or hope the person submitting the request forgets. 

Thanks for the new, lightweight, nuget package!

**Comment by Lightczx** [comment]
No,I merge the code base manually into my project.

**Comment by johngagefaulkner** [comment]
> No,I merge the code base manually into my project.

The author, @ghost1372 completed your request ~18 hours ago. https://github.com/WinUICommunity/SettingsUI/issues/5#issuecomment-1367926404
