### ISSUE TITLE
App crashes when using BackdropType Mica in settings window

### ISSUE THREAD

**Issue by DFFspace** [ghost1372/SettingsUI#6]
I noticed when adding below code to my Settings window xaml.cs and published my app as self-contained unpackaged, the app crashes when opening the window. If I take out the two lines of code the app works fine.

WASDK 1.1.0-preview3
SettingsUI 2.0.0-wasdk1.1.0-preview3

```
SystemBackdropsHelper backdropsHelper = SystemBackdropsHelper.CreateInstance();
backdropsHelper.Initialize(Instance, BackdropType.Mica);
```

**Comment by ghost1372** [comment]
Hi @DFFspace I'm trying to check it out today.
At this time, can you provide more information?

1.Can you share the contents of the settings window?
2.Can you upload a repro project?
3.Do you have the same problem with the demo project?
4.Have you used **InfoBar** control in your Settings window? If yes, this is a wasdk/winui3 bug please see [here](https://github.com/microsoft/WindowsAppSDK/issues/2353)

**Comment by ghost1372** [comment]
i tested with a new project (Self-Contained and Single File) everything is working... 

![Animation](https://user-images.githubusercontent.com/9213496/168420984-4fa21e13-6bfc-4cf6-9013-3d6b10ebf0f1.gif)

**Comment by DFFspace** [comment]
Hmmm... I also tried in on my example monitor app, and there It worked fine. The error it gives on the main app in a try/catch is this:

```
2022-05-14 21:46:28,762 [1] ERROR DFFMonitorApp.SettingsUI.Settings - System.TypeLoadException: Could not load type 'Microsoft.UI.Composition.ICompositionSupportsSystemBackdrop' from assembly 'Microsoft.InteractiveExperiences.Projection, Version=10.0.0.0, Culture=neutral, PublicKeyToken='.
   at SettingsUI.Helpers.SystemBackdropsHelper.TrySetMicaBackdrop()
   at SettingsUI.Helpers.SystemBackdropsHelper.SetBackdrop(BackdropType type)
   at SettingsUI.Helpers.SystemBackdropsHelper.Initialize(Window CurrentWindow, BackdropType CurrentType)
```

**Comment by DFFspace** [comment]
After updating my App to WASDK 1.1.0 and the SettingsUI to 2.0.6 after deploying the App to a self-contained app seems to have fixed the issue. Mica effect now working as expected!
