### ISSUE TITLE
OSVersionHelper.IsWindows11 returns false in Windows 11

### ISSUE THREAD

**Issue by rocksdanister** [ghost1372/SettingsUI#7]
The following method returns `false` in Windows 11:
https://github.com/ghost1372/SettingsUI/blob/e6bb47ffa93555b29bdd6e948d25db1b8d25ec8d/src/SettingsUI/Tools/Helpers/OSVersionHelper.cs#L24

And the following returns `true`:
https://github.com/ghost1372/SettingsUI/blob/e6bb47ffa93555b29bdd6e948d25db1b8d25ec8d/src/SettingsUI/Tools/Helpers/OSVersionHelper.cs#L29

This is because equality check assumes revision is 0 but in my build its 2
![image](https://user-images.githubusercontent.com/17554161/172129029-b5beccb7-8688-4be6-9445-4908cd2239e9.png)

On a related note why not just use:
```cs
public static bool IsWindows11_OrGreater => Environment.OSVersion.Version.Major >= 10 && Environment.OSVersion.Version.Build >= 22000;
```

Maybe remove `IsWindows11` because build number can also change in the future?

**Comment by ghost1372** [comment]
tnx i fixed issue, I do not trust the **Environment.OSVersion**, i think it does not work properly in older versions of Windows like Windows 7, XP...
