### ISSUE TITLE
Bug : ThemeHelper cannot change theme compeletely.

### ISSUE THREAD

**Issue by DavidLogic** [ghost1372/SettingsUI#8]
When you use Mica, changing themes can cause this problem like in the picture.  If you don't use Mica (IsSystemBackdropsSupported = false), then the problem disappears.

![image](https://user-images.githubusercontent.com/58322362/174522441-b7c4c60a-7af5-4802-9992-8896dca4ffdc.png)

**Comment by DavidLogic** [comment]
Mica likes cannot watch and shift itself .

**Comment by DavidLogic** [comment]
It seems that Mica cannot watch and shift itself.
Looking forward to your reply.Thanks.

**Comment by ghost1372** [comment]
Hi @DavidLogic 
Be sure to Initialize ThemeHelper like this:

`ThemeHelper.Initialize(m_window, true);
`
and for changing Theme:
```
<StackPanel x:Name="ThemePanel" Margin="10">
    <RadioButton Tag="Light" Checked="OnThemeRadioButtonChecked" Content="Light"/>
    <RadioButton Tag="Dark" Checked="OnThemeRadioButtonChecked" Content="Dark" />
    <RadioButton Tag="Default" Checked="OnThemeRadioButtonChecked" Content="Use system setting" />
</StackPanel>
```
private void OnThemeRadioButtonChecked(object sender, RoutedEventArgs e)
{
    ThemeHelper.OnThemeRadioButtonChecked(sender);
}
Everything works fine
I suggest you read the documentation and ThemeHelper class
![Animation2](https://user-images.githubusercontent.com/9213496/175763154-aa89bf1f-8eac-4337-8c07-b8466d6f0ea2.gif)

**Comment by DavidLogic** [comment]
Thanks for your reply.
I have already initialized the ThemeHelper then,but my app and the SettingUI.Demo both met this problem.So I compared them with WinUI 3 Gallery,but it didn't happen.(In this test,I've unified the variables and there is no interference)
I'm sorry that I don't describe this problem well before.
To recurrent this problem,please open the Demo and keep it running,then switch Dark color in Windows Setting.
My OS version is 10.22621.160
I think it may helps you.
Thank you.
![image](https://user-images.githubusercontent.com/58322362/175764057-d4528a5b-4cc8-4764-8dfd-dda035270144.png)

**Comment by ghost1372** [comment]
Oh I got it.
I will try to solve this problem soon.
Thanks for the report

**Comment by DavidLogic** [comment]
OK, expecting your next version!

**Comment by ghost1372** [comment]
@DavidLogic  I Added a commit 
https://github.com/ghost1372/SettingsUI/commit/a7273a9dfc659a39989de10829d1701989f1dd39

please pull latest changes from github and test Demo app.
Of course, I think the background of the buttons needs to be changed.
But for now, I would be grateful if you could test and confirm
![Animation2](https://user-images.githubusercontent.com/9213496/175771115-247d8cb7-adb2-4da4-b21f-42dc4958a644.gif)

**Comment by DavidLogic** [comment]
I‘m so sorry I didn't get the message on time.Sorry!
But I just tested it and it worked perfectly!
Thank you very much for your devotion!
This project is very helpful and makes it easier to engage in WinUI 3 ,thanks!
